### PR TITLE
Input for test

### PR DESCRIPTION
**Pull request by bguzmanrio**
This is a new feature I thought about:
Sometimes is hard to create a new regex, so I just added an edit field in order to write down your custom regEx and get it analyzed, in order to see whether it fits you.

I also cleaned up just a few parts of the code to make som functions reusable.

Hope you like!
And good job of what you have done!

### CODE REVIEW

**Comment by Wikunia** [comment]
Hi thanks for the pull request. 
There is no way to update the regex inside the code yet, right? I think it should be possible to update the code after testing some regex inside the InlineDocs. The next step would be to write some test cases and check whether they are accepted by the regex or not ;) 
But the last one would be different update!
Before I'll merge it, it would be nice to have the first feature I mentioned. What do you think?
Thanks again ;)

**Comment by bguzmanrio** [comment]
You are welcome!

What you mean by "update the regex inside the code" is to change the current regEx the user has selected with the new value the user is testing inside the input, right?

I absolutely agree with the next step you are suggesting. It should not be very complicated, I will try to think a good approach and I will let you know.

Thank you again!

**Comment by Wikunia** [comment]
Yes that's exactly what I mean. At the moment you have to copy your new regex and paste it into your code which is a bit inconvenient

**Comment by bguzmanrio** [comment]
I have just added a button to apply the new regex.
Check it out and let me know what do you think about it!

**Comment by Wikunia** [comment]
brackets-quickdocsregex-update-mismatch
These icons are overlapping now and it would be great to have something like:
`Enter` -> get new documentation for the updated regex
Or if possible live updating. 
If it's possible to update it live, it would be nice to apply the changes on enter. 
I think it's counter intuitive to retype the whole regex after clicking the edit button. The regex is only a placeholder, but it should be the value then the regex would be editable.
Thanks again man. Unfortunately I have a lot of other projects and don't have much time to integrate it myself in the near future. If you have time, it would be great if you can do the changes. If you have any further question, don't hesitate to ask. 
Have a nice weekend!

**Comment by bguzmanrio** [comment]
The icons are now gone, and only the edit icon is still there. I thought the live-reload you mentioned would be a nice improvement and therefore, I implemented it. Although I left the Apply button, but it also will update on enter

**Comment by Wikunia** [comment]
Thanks the only thing I'm missing now is that if I edit the regex it disappears in the input. I didn't mean to remove the placeholder but to set the value instead ;)

**Comment by bguzmanrio** [comment]
If I understood you right, I think it is now done

**Comment by Wikunia** [comment]
Yeah and the focus should be set :D (I think to the end of the input)

**Comment by bguzmanrio** [comment]
Sure! I was thinking about it and I completely forgot it!

**Comment by Wikunia** [comment]
Thanks for your work!

**Comment by bguzmanrio** [comment]
You are welcome!

**Pull request merged**
